# Production Configuration Override
# This file overrides development settings for production

environment: production

# Production Database Settings
database:
  sqlite:
    path: "/var/lib/trading-bot/trading_bot.db"
  redis:
    host: "redis-cluster.local"
    port: 6379
    password: ${REDIS_PASSWORD}
  mongodb:
    host: "mongodb-cluster.local"
    port: 27017
    username: ${MONGODB_USERNAME}
    password: ${MONGODB_PASSWORD}

# Production Trading Settings
trading:
  exchanges:
    binance:
      sandbox: false
      testnet: false
    alpaca:
      base_url: "https://api.alpaca.markets"

# Enhanced Security for Production
security:
  api_rate_limits:
    requests_per_minute: 50  # More conservative
    burst_limit: 5
  
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"

# Production Logging
logging:
  level: "WARNING"
  files:
    main: "/var/log/trading-bot/main.log"
    trading: "/var/log/trading-bot/trading.log"
    swarm: "/var/log/trading-bot/swarm.log"
    errors: "/var/log/trading-bot/errors.log"

# Production Monitoring
monitoring:
  prometheus:
    enabled: true
    port: 8000
  
  grafana:
    enabled: true
    dashboard_url: "https://monitoring.trading-bot.local"
  
  alerts:
    email:
      enabled: true
      recipients:
        - "admin@trading-bot.local"
        - "alerts@trading-bot.local"

# Production Performance Settings
raspberry_pi:
  performance:
    cpu_governor: "performance"
    swap_usage_threshold: 30.0