name: Dependency Updates

on:
  schedule:
    # Run weekly on Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-dependencies:
    name: Check for Dependency Updates
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pip-tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-tools pip-audit

      - name: Check for outdated packages
        id: outdated
        run: |
          pip install -r requirements.txt || true
          pip list --outdated > outdated.txt
          cat outdated.txt
        continue-on-error: true

      - name: Create issue for outdated dependencies
        if: steps.outdated.outcome == 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const outdated = fs.readFileSync('outdated.txt', 'utf8');
            
            if (outdated.trim().split('\n').length > 2) {
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: '📦 Dependency Updates Available',
                body: `## Outdated Dependencies\n\nThe following packages have updates available:\n\n\`\`\`\n${outdated}\n\`\`\`\n\nPlease review and update as needed.`,
                labels: ['dependencies', 'automated']
              });
            }
